echo Exporting ONNX...
python3 save_onnx.py
echo Exporting CoreML...
python3 save_coreml.py
echo Exporting Torchscript...
python3 save_torchscript.py
echo Copying models...
cp sfd_detector.mlmodel /Users/josebouza/Projects/Face\ Anonymizer/Face\ Anonymizer/models
cp keypointrcnn.pt /Users/josebouza/Projects/Face\ Anonymizer/Face\ Anonymizer/models
